### ISSUE TITLE
Error "FATAL: Failed to open a temp file for chrom lengths"

### ISSUE THREAD

**Issue by haowuisu** [MikeAxtell/bam2wig#6]
I am trying to use bam2wig to convert a bam file to a bigwig file for genome visualization. I got an issue at the third step of bam2wig, and the program failed to open the temp file "chr_lens_temp.txt".

I have installed and loaded wigtobigwig. My BAM file has been sorted and indexed. The header is as follows,

$ samtools view -H PB_ATAC_T2.filtered.bam
@hd VN:1.5 SO:coordinate
@sq SN:1 LN:307041717
@sq SN:2 LN:244442276
@sq SN:3 LN:235667834
@sq SN:4 LN:246994605
@sq SN:5 LN:223902240
@sq SN:6 LN:174033170
@sq SN:7 LN:182381542
@sq SN:8 LN:181122637
@sq SN:9 LN:159769782
@sq SN:10 LN:150982314
@sq SN:Pt LN:140384
@sq SN:Mt LN:569630
....

The code I run the program was as follows:

module load bam2wig
module load wigtobigwig

bam2wig PB_ATAC_T2.filtered.bam

Why did the error occur? How to fix it?

Thanks.

**Comment by MikeAxtell** [comment]
That looks like line 633 of code and only reason I can see why that line would fail is that you don't have permissions to create and open a new file in your working directory, smells like a permissions issue you need to resolve if you are using an HPC cluster.

I will also make a suggestion to investigate deeptools (https://deeptools.readthedocs.io/en/develop/)  for this purpose instead of using my crummy old bam2wig script. deeptools is much more actively maintained and less likely to be buggy !  Specifically deeptools bamCoverage (https://deeptools.readthedocs.io/en/develop/content/tools/bamCoverage.html) will do what you need.

Good luck,
Mike

**Comment by haowuisu** [comment]
Great, thanks!
